name: 'portfolio-monalisa-dev'
services:
  app:
    build: .
    restart: on-failure:3
    volumes:
      - portfolio-monalisa_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4200:3000
  browserless:
    image: ghcr.io/browserless/chromium:latest
    restart: on-failure:3
    user: root
    volumes:
      - portfolio-monalisa_data:/usr/src/app/user-data-dir
    environment:
      - CORS=true
    ports:
      - 1202:3000

volumes:
  portfolio-monalisa_static:
    external: true
  portfolio-monalisa_data:
    external: true
