name: 'portfolio-monalisa-dev'
services:
  app:
    build: .
    restart: on-failure:3
    volumes:
      - portfolio-monalisa_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4200:3000

volumes:
  portfolio-monalisa_static:
    external: true
