name: 'portfolio-monalisa-dev'
services:
  app:
    # image: 'ghcr.io/algostract/portfolio-monalisa:latest'
    build: .
    restart: on-failure:3
    volumes:
      - type: bind
        source: ./static
        target: /app/static
    env_file:
      - .env.prod
    ports:
      - 4101:3000
