version: '3.9'
services:
  app:
    image: 'ghcr.io/algostract/portfolio-monalisa:latest'
    volumes:
      - portfolio-monalisa_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4200:3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  portfolio-monalisa_static:
    external: true

networks:
  front-tier:
    driver: overlay
