name: Nuxt CD

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NITRO_PRESET: ${{ vars.NITRO_PRESET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Bulid Artifacts
        run: npm run build

      - name: Upload artifact to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          overwrite: true
          source: '.output, testimonials.yml'
          target: '~/portfolio-monalisa'
